import uuid
from sqlmodel import (
    Field,
    SQLModel,
)


class MarineCampaign(SQLModel, table=True):
    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    # need:
    # - owner
    # - slug, which can likely be autogenerated
    # - name, which would be l18n friendly
    # - 1:m relationship to project survey missions
    # - 1:m relationship to project links
