import uuid
from sqlmodel import (
    Field,
    SQLModel,
)


class SldProject(SQLModel, table=True):
    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    # need a slug, which can likely be autogenerated
    # also need a name, which would be l18n friendly
    # need a 1:m relationship to project survey missions
    # need a 1:m relationship to project links
