name: seis-lab-data

x-common-image: &common-image "${IMAGE_URL}"
x-db-image: &db-image "postgis/postgis:17-3.5-alpine"

x-common-env: &common-env
  SEIS_LAB_DATA__DEBUG: true
  SEIS_LAB_DATA__DATABASE_DSN: postgresql+psycopg://sld:sldpass@db:5432/seis_lab_data
  SEIS_LAB_DATA__TEST_DATABASE_DSN: postgresql+psycopg://sld:sldpass@test-db:5432/seis_lab_data_test
  SEIS_LAB_DATA__MESSAGE_BROKER_DSN: redis://message-broker:6379

services:

  message-broker:
    image: redis:8
    ports:
      - target: 6379
        published: 6379
    healthcheck:
      test: "redis-cli PING | grep PONG"

  db:
    image: *db-image
    environment:
      POSTGRES_DB: seis_lab_data
      POSTGRES_USER: sld
      POSTGRES_PASSWORD: sldpass
    healthcheck:
      test: "pg_isready -d seis_lab_data -U sld"
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s

  webapp:
    image: *common-image
    environment:
      <<: *common-env
      SEIS_LAB_DATA__BIND_HOST: 0.0.0.0
      SEIS_LAB_DATA__BIND_PORT: 5000
      SEIS_LAB_DATA__PUBLIC_URL: http://localhost:8888
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sld-router.rule=PathRegexp(`^/`)"
      - "traefik.http.routers.sld-router.entrypoints=web"
      - "traefik.http.services.sld-service.loadbalancer.server.port=5000"
    depends_on:
      db:
        condition: service_healthy
      message-broker:
        condition: service_healthy

  processing-worker:
    image: *common-image
    command:
      - "run-processing-worker"
    environment:
      <<: *common-env

  end-to-end-tester:
    image: mcr.microsoft.com/playwright/python:v1.53.0-noble
    profiles:
      - "e2e-test"
    volumes:
      - type: bind
        source: $PWD/tests/e2e
        target: /tests/e2e
        read_only: true
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        pip install "playwright==1.53.0" pytest-playwright
        pytest --base-url=http://webapp:5000 /tests

  test-db:
    image: *db-image
    environment:
      POSTGRES_DB: seis_lab_data_test
      POSTGRES_USER: sld
      POSTGRES_PASSWORD: sldpass
    healthcheck:
      test: "pg_isready -d seis_lab_data_test -U sld"
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
