name: seis-lab-data

x-auth-image: &auth-image "ghcr.io/goauthentik/server:2025.8.0-rc6"
x-auth-admin-token: &auth-admin-token "admin123"
x-common-image: &common-image "${IMAGE_URL}"
x-db-image: &db-image "postgis/postgis:17-3.5-alpine"
x-auth-client-id: &auth-client-id "sld-client-id"
x-auth-client-secret: &auth-client-secret "sld-client-secret"
x-auth-redirect-url: &auth-redirect-url "http://localhost:8888/oauth2/callback"

x-common-env: &common-env
  SEIS_LAB_DATA__DEBUG: true
  SEIS_LAB_DATA__DATABASE_DSN: postgresql+psycopg://sld:sldpass@db:5432/seis_lab_data
  SEIS_LAB_DATA__TEST_DATABASE_DSN: postgresql+psycopg://sld:sldpass@test-db:5432/seis_lab_data_test
  SEIS_LAB_DATA__MESSAGE_BROKER_DSN: redis://message-broker:6379

x-common-auth-env: &common-auth-env
  AUTHENTIK_LOG_LEVEL: debug
  AUTHENTIK_SECRET_KEY: mysecret
  AUTHENTIK_REDIS__HOST: message-broker
  AUTHENTIK_POSTGRESQL__HOST: auth-db
  AUTHENTIK_POSTGRESQL__USER: authentik
  AUTHENTIK_POSTGRESQL__NAME: authentik
  AUTHENTIK_POSTGRESQL__PASSWORD: authentik_pass
  AUTHENTIK_WEB__PATH: /auth/
  SEIS_LAB_DATA_CLIENT_ID: *auth-client-id
  SEIS_LAB_DATA_CLIENT_SECRET: *auth-client-secret
  SEIS_LAB_DATA_REDIRECT_URI: *auth-redirect-url

x-common-volumes: &common-volumes
  - type: bind
    source: ../tests/data
    target: /data

services:

  web-gateway:
    image: traefik:v3
    ports:
      - target: 80
        published: 8888
      # traefik API and dashboard
      - target: 8080
        published: 8887
    configs:
      - source: traefik-conf
        target: /traefik.toml
    command: --configFile /traefik.toml
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

  auth-db:
    image: postgres:17
    environment:
      POSTGRES_DB: authentik
      POSTGRES_USER: authentik
      POSTGRES_PASSWORD: authentik_pass
    healthcheck:
      test: "pg_isready -d authentik -U authentik"
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s

  auth-webapp:
    image: *auth-image
    command: server
    environment:
      <<: *common-auth-env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-router.rule=PathRegexp(`^/auth/`)"
      - "traefik.http.routers.auth-router.entrypoints=web"
      - "traefik.http.routers.auth-router.priority=100"
      - "traefik.http.services.auth-service.loadbalancer.server.port=9000"
    depends_on:
      auth-db:
        condition: service_healthy
      message-broker:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import requests; requests.get(\"http://localhost:9000/auth/-/health/ready/\").raise_for_status()'"]
      start_period: 30s
      interval: 10s
      retries: 10
      timeout: 5s

  auth-worker:
    image: *auth-image
    command: worker
    environment:
      <<: *common-auth-env
      AUTHENTIK_BOOTSTRAP_PASSWORD: admin123
      AUTHENTIK_BOOTSTRAP_TOKEN: *auth-admin-token
      AUTHENTIK_BOOTSTRAP_EMAIL: akadmin@email.com
    volumes:
      - type: bind
        source: ./authentik/sld-auth-blueprint-dev.yaml
        target: /blueprints/custom/sld-auth-blueprint-dev.yaml
        read_only: true
    depends_on:
      auth-db:
        condition: service_healthy
      message-broker:
        condition: service_healthy

  message-broker:
    image: redis:8
    ports:
      - target: 6379
        published: 6379
    healthcheck:
      test: "redis-cli PING | grep PONG"

  db:
    image: *db-image
    environment:
      POSTGRES_DB: seis_lab_data
      POSTGRES_USER: sld
      POSTGRES_PASSWORD: sldpass
    healthcheck:
      test: "pg_isready -d seis_lab_data -U sld"
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s

  webapp:
    image: *common-image
    environment:
      <<: *common-env
      SEIS_LAB_DATA__BIND_HOST: 0.0.0.0
      SEIS_LAB_DATA__BIND_PORT: 5000
      SEIS_LAB_DATA__PUBLIC_URL: http://localhost:8888
      SEIS_LAB_DATA__AUTH_EXTERNAL_BASE_URL: http://localhost:8888/auth
      SEIS_LAB_DATA__AUTH_INTERNAL_BASE_URL: http://auth-webapp:9000/auth
      SEIS_LAB_DATA__AUTH_CLIENT_ID: *auth-client-id
      SEIS_LAB_DATA__AUTH_CLIENT_SECRET: *auth-client-secret
      SEIS_LAB_DATA__WEBMAP_BASE_TILE_LAYER_URL: http://localhost:8888/tiles/small-emodnet-bathymetry-l2/{z}/{x}/{y}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sld-router.rule=PathRegexp(`^/`)"
      - "traefik.http.routers.sld-router.entrypoints=web"
      - "traefik.http.services.sld-service.loadbalancer.server.port=5000"
    depends_on:
      db:
        condition: service_healthy
      message-broker:
        condition: service_healthy
      auth-webapp:
        condition: service_healthy
    volumes:
      *common-volumes

  processing-worker:
    image: *common-image
    command:
      - "run-processing-worker"
    environment:
      <<: *common-env
    volumes:
      *common-volumes

  martin-tile-server:
    image: ghcr.io/maplibre/martin:martin-v0.19.3
    command: ["--config", "/martin-conf"]
    environment:
      SLD_DATABASE_URL: postgres://sld:sldpass@db/seis_lab_data
    configs:
      - martin-conf
    volumes:
      - type: bind
        source: ../tests/data/pmtiles
        target: /pmtiles
        read_only: true
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.martin-stripprefix.stripprefix.prefixes=/tiles"
      - "traefik.http.routers.martin-router.entrypoints=web"
      - "traefik.http.routers.martin-router.rule=PathPrefix(`/tiles`)"
      - "traefik.http.routers.martin-router.priority=90"
      - "traefik.http.routers.martin-router.middlewares=martin-stripprefix"
      - "traefik.http.services.martin.loadbalancer.server.port=3000"

  test-db:
    image: *db-image
    environment:
      POSTGRES_DB: seis_lab_data_test
      POSTGRES_USER: sld
      POSTGRES_PASSWORD: sldpass
    healthcheck:
      test: "pg_isready -d seis_lab_data_test -U sld"
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s


configs:

  traefik-conf:
    file: ./traefik/dev-config.toml

  martin-conf:
    content: |
      base_path: /tiles
      listen_addresses: '0.0.0.0:3000'
      web_ui: disable
      cache_size_mb: 0
      postgres:
        connection_string: $${SLD_DATABASE_URL}
        auto_publish: false

        tables:

          projects:
            schema: public
            table: project
            srid: 4326
            geometry_column: bbox_4326
            id_column: ~
            geometry_type: POLYGON
            buffer: 256
            properties:
              id: uuid
              name: jsonb

          survey_missions:
            schema: public
            table: surveymission
            srid: 4326
            geometry_column: bbox_4326
            id_column: ~
            geometry_type: POLYGON
            buffer: 256
            properties:
              id: uuid
              name: jsonb

          survey_related_records:
            schema: public
            table: surveyrelatedrecord
            srid: 4326
            geometry_column: bbox_4326
            id_column: ~
            geometry_type: POLYGON
            buffer: 256
            properties:
              id: uuid
              name: jsonb

      pmtiles:
        paths:
          - /pmtiles
