# This blueprint provides a 2-stage enrollment flow which gathers the user's:
#
# - username
# - password
# - email
#
# The flow preforms email validation before activating the user, which means authentik needs to have been
# configured with suitable email settings.
version: 1
metadata:
  name: Enrollment with email verification
  labels:
    blueprints.goauthentik.io/instantiate: "true"
entries:
  - identifiers:
      slug: email-enrollment-flow
    id: email-enrollment-flow
    model: authentik_flows.flow
    attrs:
      name: Mail verification enrollment Flow
      title: Welcome to authentik!
      designation: enrollment
      authentication: require_unauthenticated
  - identifiers:
      name: email-enrollment-email-verification
    id: email-enrollment-email-verification
    model: authentik_stages_email.emailstage
    attrs:
      use_global_settings: true
      template: email/account_confirmation.html
      activate_user_on_success: true
  - identifiers:
      name: email-enrollment-prompt-second
    id: email-enrollment-prompt-second
    model: authentik_stages_prompt.promptstage
    attrs:
      fields:
        - !Find [ authentik_stages_prompt.prompt, [ name, "prompt-field-name" ]]
        - !Find [ authentik_stages_prompt.prompt, [ name, "prompt-field-email" ]]
  - identifiers:
      name: email-enrollment-prompt-first
    id: email-enrollment-prompt-first
    model: authentik_stages_prompt.promptstage
    attrs:
      fields:
        - !Find [ authentik_stages_prompt.prompt, [ name, "prompt-field-username" ]]
        - !Find [ authentik_stages_prompt.prompt, [ name, "prompt-field-password" ]]
        - !Find [ authentik_stages_prompt.prompt, [ name, "prompt-field-password-repeat" ]]
  - identifiers:
      name: email-enrollment-user-login
    id: email-enrollment-user-login
    model: authentik_stages_user_login.userloginstage
  - identifiers:
      name: email-enrollment-user-write
    id: email-enrollment-user-write
    model: authentik_stages_user_write.userwritestage
    attrs:
      create_users_as_inactive: true
      user_creation_mode: always_create
  - identifiers:
      target: !KeyOf email-enrollment-flow
      stage: !KeyOf email-enrollment-prompt-first
      order: 10
    model: authentik_flows.flowstagebinding
  - identifiers:
      target: !KeyOf email-enrollment-flow
      stage: !KeyOf email-enrollment-prompt-second
      order: 11
    model: authentik_flows.flowstagebinding
  - identifiers:
      target: !KeyOf email-enrollment-flow
      stage: !KeyOf email-enrollment-user-write
      order: 20
    model: authentik_flows.flowstagebinding
  - identifiers:
      target: !KeyOf email-enrollment-flow
      stage: !KeyOf email-enrollment-email-verification
      order: 30
    model: authentik_flows.flowstagebinding
  - identifiers:
      target: !KeyOf email-enrollment-flow
      stage: !KeyOf email-enrollment-user-login
      order: 100
    model: authentik_flows.flowstagebinding
