# This blueprint specifies an authentication flow that enables user registration. It is used by the
# sld-authorization blueprint.
version: 1
metadata:
  name: Authentication flow for SeisLabData.
  labels:
    blueprints.goauthentik.io/instantiate: "true"
context: {}
entries:
  - identifiers:
      slug: sld-authentication-flow
    model: authentik_flows.flow
    attrs:
      authentication: require_unauthenticated
      denied_action: message_continue
      designation: authentication
      layout: stacked
      name: sld authentication flow
      policy_engine_mode: any
      title: SeisLabData authentication
    conditions: []
    permissions: []
    state: present
  - identifiers:
      name: sld-identification
    model: authentik_stages_identification.identificationstage
    attrs:
      case_insensitive_matching: true
      password_stage: !Find [authentik_stages_password.passwordstage, [name, "default-authentication-password"]]
      pretend_user_exists: true
      show_matched_user: true
      user_fields:
      - email
    conditions: []
    permissions: []
    state: present
  - identifiers:
      order: 0
      pk: 99bba28f-96b5-434f-b37e-9f64a9d11004
      stage: !Find [authentik_stages_identification.identificationstage, [name, "sld-identification"]]
      target: !Find [authentik_flows.flow, [slug, "sld-authentication-flow"]]
    model: authentik_flows.flowstagebinding
    attrs:
      invalid_response_action: retry
      policy_engine_mode: any
      re_evaluate_policies: true
    conditions: []
    permissions: []
    state: present
  - identifiers:
      order: 10
      pk: 4b2515bf-b6ad-4b30-92c4-27ff3f37925e
      stage: !Find [authentik_stages_authenticator_validate.authenticatorvalidatestage, [name, "default-identification-mfa-validation"]]
      target: !Find [authentik_flows.flow, [slug, "sld-authentication-flow"]]
    model: authentik_flows.flowstagebinding
    attrs:
      invalid_response_action: retry
      policy_engine_mode: any
      re_evaluate_policies: true
    conditions: []
    permissions: []
    state: present
  - identifiers:
      order: 20
      pk: 6d142b04-56f0-4f4b-acbe-d1d0494d3425
      stage: !Find [authentik_stages_user_login.userloginstage, [name, "default-authentication-login"]]
      target: !Find [authentik_flows.flow, [slug, "sld-authentication-flow"]]
    model: authentik_flows.flowstagebinding
    attrs:
      invalid_response_action: retry
      policy_engine_mode: any
      re_evaluate_policies: true
    conditions: []
    permissions: []
    state: present
