"""re-add relationship as a json for localization

Revision ID: f12ba98fcd56
Revises: b3ab2f751e94
Create Date: 2025-12-08 11:49:12.115528

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f12ba98fcd56"
down_revision: Union[str, Sequence[str], None] = "b3ab2f751e94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "surveyrelatedrecordselflink",
        sa.Column("relation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("surveyrelatedrecordselflink", "relation")
    # ### end Alembic commands ###
