"""added missing indexes

Revision ID: 84bb9d5b75b1
Revises: 525590ae0a8e
Create Date: 2025-12-02 22:13:01.048631

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "84bb9d5b75b1"
down_revision: Union[str, Sequence[str], None] = "525590ae0a8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_project_name_gin",
        "project",
        ["name"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_recordasset_name_gin",
        "recordasset",
        ["name"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_recordasset_survey_related_record_id"),
        "recordasset",
        ["survey_related_record_id"],
        unique=False,
    )
    op.create_index(
        "idx_surveymission_name_gin",
        "surveymission",
        ["name"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_surveymission_project_id"),
        "surveymission",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "idx_surveyrelatedrecord_name_gin",
        "surveyrelatedrecord",
        ["name"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_surveyrelatedrecord_survey_mission_id"),
        "surveyrelatedrecord",
        ["survey_mission_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_surveyrelatedrecord_survey_mission_id"),
        table_name="surveyrelatedrecord",
    )
    op.drop_index(
        "idx_surveyrelatedrecord_name_gin",
        table_name="surveyrelatedrecord",
        postgresql_using="gin",
    )
    op.drop_index(op.f("ix_surveymission_project_id"), table_name="surveymission")
    op.drop_index(
        "idx_surveymission_name_gin", table_name="surveymission", postgresql_using="gin"
    )
    op.drop_index(
        op.f("ix_recordasset_survey_related_record_id"), table_name="recordasset"
    )
    op.drop_index(
        "idx_recordasset_name_gin", table_name="recordasset", postgresql_using="gin"
    )
    op.drop_index("idx_project_name_gin", table_name="project", postgresql_using="gin")
    # ### end Alembic commands ###
