"""remove relationship name

Revision ID: b3ab2f751e94
Revises: 84bb9d5b75b1
Create Date: 2025-12-08 11:48:40.831498

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "b3ab2f751e94"
down_revision: Union[str, Sequence[str], None] = "84bb9d5b75b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("surveyrelatedrecordselflink", "relation")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "surveyrelatedrecordselflink",
        sa.Column(
            "relation", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
