"""added mission relative path

Revision ID: 4938ddb83978
Revises: de9ad1b3280b
Create Date: 2025-09-02 12:10:20.854238

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "4938ddb83978"
down_revision: Union[str, Sequence[str], None] = "de9ad1b3280b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "surveymission",
        sa.Column("relative_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("surveymission", "relative_path")
    # ### end Alembic commands ###
