"""added temporal columns to project

Revision ID: 38ceed03d957
Revises: 7aa0df84b581
Create Date: 2025-10-31 16:58:53.092527

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "38ceed03d957"
down_revision: Union[str, Sequence[str], None] = "7aa0df84b581"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("project", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column(
        "project", sa.Column("temporal_extent_begin", sa.Date(), nullable=True)
    )
    op.add_column("project", sa.Column("temporal_extent_end", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "temporal_extent_end")
    op.drop_column("project", "temporal_extent_begin")
    op.drop_column("project", "updated_at")
    op.drop_column("project", "created_at")
    # ### end Alembic commands ###
