"""added relative_path to survey related record

Revision ID: 3a7a952412de
Revises: 4938ddb83978
Create Date: 2025-09-02 14:29:09.158797

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "3a7a952412de"
down_revision: Union[str, Sequence[str], None] = "4938ddb83978"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "surveyrelatedrecord",
        sa.Column("relative_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("surveyrelatedrecord", "relative_path")
    # ### end Alembic commands ###
