"""increase slug size

Revision ID: de9ad1b3280b
Revises: 73ae4b3d0f11
Create Date: 2025-09-02 10:42:26.405548

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "de9ad1b3280b"
down_revision: Union[str, Sequence[str], None] = "73ae4b3d0f11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project",
        "slug",
        existing_type=sa.VARCHAR(length=50),
        type_=sqlmodel.sql.sqltypes.AutoString(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "recordasset",
        "slug",
        existing_type=sa.VARCHAR(length=50),
        type_=sqlmodel.sql.sqltypes.AutoString(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "surveymission",
        "slug",
        existing_type=sa.VARCHAR(length=50),
        type_=sqlmodel.sql.sqltypes.AutoString(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "surveyrelatedrecord",
        "slug",
        existing_type=sa.VARCHAR(length=50),
        type_=sqlmodel.sql.sqltypes.AutoString(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "surveyrelatedrecord",
        "slug",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "surveymission",
        "slug",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "recordasset",
        "slug",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "project",
        "slug",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
