"""add-project-bbox

Revision ID: 941230297c91
Revises: bf61054ff56d
Create Date: 2025-10-18 21:46:12.654705

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "941230297c91"
down_revision: Union[str, Sequence[str], None] = "bf61054ff56d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_geospatial_column(
        "project",
        sa.Column(
            "bbox_4326",
            Geometry(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
    )
    op.create_geospatial_index(
        "idx_project_bbox_4326",
        "project",
        ["bbox_4326"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_project_bbox_4326",
        table_name="project",
        postgresql_using="gist",
        column_name="bbox_4326",
    )
    op.drop_geospatial_column("project", "bbox_4326")
    # ### end Alembic commands ###
