"""add projects model

Revision ID: 88b483de5639
Revises: bcc1fbd80797
Create Date: 2025-09-01 14:11:11.809405

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "88b483de5639"
down_revision: Union[str, Sequence[str], None] = "bcc1fbd80797"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("DRAFT", "PUBLISHED", name="projectstatus").create(op.get_bind())
    op.create_table(
        "project",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "owner", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "description", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "DRAFT", "PUBLISHED", name="projectstatus", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("root_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column("links", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_project_owner"), "project", ["owner"], unique=False)
    op.create_index(op.f("ix_project_slug"), "project", ["slug"], unique=True)
    op.add_column("surveymission", sa.Column("project_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(None, "surveymission", "project", ["project_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "surveymission", type_="foreignkey")
    op.drop_column("surveymission", "project_id")
    op.drop_index(op.f("ix_project_slug"), table_name="project")
    op.drop_index(op.f("ix_project_owner"), table_name="project")
    op.drop_table("project")
    sa.Enum("DRAFT", "PUBLISHED", name="projectstatus").drop(op.get_bind())
    # ### end Alembic commands ###
