"""add cascade on remaining fks

Revision ID: fc1dc583bc5f
Revises: 2765ad987c36
Create Date: 2025-09-04 11:40:11.238515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "fc1dc583bc5f"
down_revision: Union[str, Sequence[str], None] = "2765ad987c36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("surveymission_project_id_fkey"), "surveymission", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "surveymission", "project", ["project_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "surveyrelatedrecord",
        "dataset_category_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.alter_column(
        "surveyrelatedrecord", "domain_type_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "surveyrelatedrecord",
        "workflow_stage_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.drop_constraint(
        op.f("surveyrelatedrecord_dataset_category_id_fkey"),
        "surveyrelatedrecord",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("surveyrelatedrecord_survey_mission_id_fkey"),
        "surveyrelatedrecord",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("surveyrelatedrecord_domain_type_id_fkey"),
        "surveyrelatedrecord",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("surveyrelatedrecord_workflow_stage_id_fkey"),
        "surveyrelatedrecord",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "surveyrelatedrecord",
        "datasetcategory",
        ["dataset_category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "surveyrelatedrecord",
        "workflowstage",
        ["workflow_stage_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "surveyrelatedrecord",
        "domaintype",
        ["domain_type_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "surveyrelatedrecord",
        "surveymission",
        ["survey_mission_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "surveyrelatedrecord", type_="foreignkey")
    op.drop_constraint(None, "surveyrelatedrecord", type_="foreignkey")
    op.drop_constraint(None, "surveyrelatedrecord", type_="foreignkey")
    op.drop_constraint(None, "surveyrelatedrecord", type_="foreignkey")
    op.create_foreign_key(
        op.f("surveyrelatedrecord_workflow_stage_id_fkey"),
        "surveyrelatedrecord",
        "workflowstage",
        ["workflow_stage_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("surveyrelatedrecord_domain_type_id_fkey"),
        "surveyrelatedrecord",
        "domaintype",
        ["domain_type_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("surveyrelatedrecord_survey_mission_id_fkey"),
        "surveyrelatedrecord",
        "surveymission",
        ["survey_mission_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("surveyrelatedrecord_dataset_category_id_fkey"),
        "surveyrelatedrecord",
        "datasetcategory",
        ["dataset_category_id"],
        ["id"],
    )
    op.alter_column(
        "surveyrelatedrecord",
        "workflow_stage_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.alter_column(
        "surveyrelatedrecord", "domain_type_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "surveyrelatedrecord",
        "dataset_category_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.drop_constraint(None, "surveymission", type_="foreignkey")
    op.create_foreign_key(
        op.f("surveymission_project_id_fkey"),
        "surveymission",
        "project",
        ["project_id"],
        ["id"],
    )
    # ### end Alembic commands ###
