"""add cascade deletes on asset

Revision ID: 2765ad987c36
Revises: c8017a902ddc
Create Date: 2025-09-04 11:33:17.289280

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "2765ad987c36"
down_revision: Union[str, Sequence[str], None] = "c8017a902ddc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("recordasset_survey_related_record_id_fkey"),
        "recordasset",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "recordasset",
        "surveyrelatedrecord",
        ["survey_related_record_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "recordasset", type_="foreignkey")
    op.create_foreign_key(
        op.f("recordasset_survey_related_record_id_fkey"),
        "recordasset",
        "surveyrelatedrecord",
        ["survey_related_record_id"],
        ["id"],
    )
    # ### end Alembic commands ###
