"""added delete cascade

Revision ID: 525590ae0a8e
Revises: 2c285f1acbc0
Create Date: 2025-12-02 21:45:47.847754

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "525590ae0a8e"
down_revision: Union[str, Sequence[str], None] = "2c285f1acbc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("surveyrelatedrecordselflink_subject_id_fkey"),
        "surveyrelatedrecordselflink",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("surveyrelatedrecordselflink_related_to_id_fkey"),
        "surveyrelatedrecordselflink",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "surveyrelatedrecordselflink",
        "surveyrelatedrecord",
        ["subject_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "surveyrelatedrecordselflink",
        "surveyrelatedrecord",
        ["related_to_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "surveyrelatedrecordselflink", type_="foreignkey")
    op.drop_constraint(None, "surveyrelatedrecordselflink", type_="foreignkey")
    op.create_foreign_key(
        op.f("surveyrelatedrecordselflink_related_to_id_fkey"),
        "surveyrelatedrecordselflink",
        "surveyrelatedrecord",
        ["related_to_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("surveyrelatedrecordselflink_subject_id_fkey"),
        "surveyrelatedrecordselflink",
        "surveyrelatedrecord",
        ["subject_id"],
        ["id"],
    )
    # ### end Alembic commands ###
