"""adding record self relations

Revision ID: 2c285f1acbc0
Revises: a1afa4a3db11
Create Date: 2025-11-29 19:48:24.598532

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "2c285f1acbc0"
down_revision: Union[str, Sequence[str], None] = "a1afa4a3db11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "surveyrelatedrecordselflink",
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("related_to_id", sa.Uuid(), nullable=False),
        sa.Column(
            "relation", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["related_to_id"],
            ["surveyrelatedrecord.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["surveyrelatedrecord.id"],
        ),
        sa.PrimaryKeyConstraint("subject_id", "related_to_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("surveyrelatedrecordselflink")
    # ### end Alembic commands ###
