"""removed-slug-field

Revision ID: bf61054ff56d
Revises: fc1dc583bc5f
Create Date: 2025-09-18 21:48:25.264354

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "bf61054ff56d"
down_revision: Union[str, Sequence[str], None] = "fc1dc583bc5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_slug"), table_name="project")
    op.drop_column("project", "slug")
    op.drop_index(op.f("ix_surveymission_slug"), table_name="surveymission")
    op.drop_column("surveymission", "slug")
    op.drop_index(op.f("ix_surveyrelatedrecord_slug"), table_name="surveyrelatedrecord")
    op.drop_column("surveyrelatedrecord", "slug")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "surveyrelatedrecord",
        sa.Column("slug", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.create_index(
        op.f("ix_surveyrelatedrecord_slug"),
        "surveyrelatedrecord",
        ["slug"],
        unique=True,
    )
    op.add_column(
        "surveymission",
        sa.Column("slug", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.create_index(
        op.f("ix_surveymission_slug"), "surveymission", ["slug"], unique=True
    )
    op.add_column(
        "project",
        sa.Column("slug", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.create_index(op.f("ix_project_slug"), "project", ["slug"], unique=True)
    # ### end Alembic commands ###
