"""add is_valid to assets

Revision ID: c8017a902ddc
Revises: 3a7a952412de
Create Date: 2025-09-04 10:06:39.933549

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c8017a902ddc"
down_revision: Union[str, Sequence[str], None] = "3a7a952412de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recordasset", sa.Column("is_valid", sa.Boolean(), nullable=False))
    op.add_column(
        "recordasset",
        sa.Column("relative_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "recordasset",
        sa.Column("links", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.drop_index(op.f("ix_recordasset_slug"), table_name="recordasset")
    op.drop_column("recordasset", "slug")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recordasset",
        sa.Column("slug", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.create_index(op.f("ix_recordasset_slug"), "recordasset", ["slug"], unique=True)
    op.drop_column("recordasset", "links")
    op.drop_column("recordasset", "relative_path")
    op.drop_column("recordasset", "is_valid")
    # ### end Alembic commands ###
