"""initial

Revision ID: 542e8725530e
Revises:
Create Date: 2025-08-28 16:16:02.805767

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "542e8725530e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("DRAFT", "PUBLISHED", name="surveyrelatedrecordstatus").create(
        op.get_bind()
    )
    sa.Enum("DRAFT", "PUBLISHED", name="surveymissionstatus").create(op.get_bind())
    sa.Enum("DRAFT", "PUBLISHED", name="marinecampaignstatus").create(op.get_bind())
    op.create_table(
        "datasetcategory",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "domaintype",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "marinecampaign",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "owner", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "DRAFT", "PUBLISHED", name="marinecampaignstatus", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("root_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column("links", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_marinecampaign_owner"), "marinecampaign", ["owner"], unique=False
    )
    op.create_index(
        op.f("ix_marinecampaign_slug"), "marinecampaign", ["slug"], unique=True
    )
    op.create_table(
        "workflowstage",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "surveymission",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "owner", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("marine_campaign_id", sa.Uuid(), nullable=False),
        sa.Column("links", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "DRAFT", "PUBLISHED", name="surveymissionstatus", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["marine_campaign_id"],
            ["marinecampaign.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_surveymission_owner"), "surveymission", ["owner"], unique=False
    )
    op.create_index(
        op.f("ix_surveymission_slug"), "surveymission", ["slug"], unique=True
    )
    op.create_table(
        "surveyrelatedrecord",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "owner", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "DRAFT",
                "PUBLISHED",
                name="surveyrelatedrecordstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column("survey_mission_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_category_id", sa.Uuid(), nullable=False),
        sa.Column("domain_type_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_stage_id", sa.Uuid(), nullable=False),
        sa.Column("links", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset_category_id"],
            ["datasetcategory.id"],
        ),
        sa.ForeignKeyConstraint(
            ["domain_type_id"],
            ["domaintype.id"],
        ),
        sa.ForeignKeyConstraint(
            ["survey_mission_id"],
            ["surveymission.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_stage_id"],
            ["workflowstage.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_surveyrelatedrecord_owner"),
        "surveyrelatedrecord",
        ["owner"],
        unique=False,
    )
    op.create_index(
        op.f("ix_surveyrelatedrecord_slug"),
        "surveyrelatedrecord",
        ["slug"],
        unique=True,
    )
    op.create_table(
        "recordasset",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("survey_related_record_id", sa.Uuid(), nullable=False),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["survey_related_record_id"],
            ["surveyrelatedrecord.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recordasset_slug"), "recordasset", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recordasset_slug"), table_name="recordasset")
    op.drop_table("recordasset")
    op.drop_index(op.f("ix_surveyrelatedrecord_slug"), table_name="surveyrelatedrecord")
    op.drop_index(
        op.f("ix_surveyrelatedrecord_owner"), table_name="surveyrelatedrecord"
    )
    op.drop_table("surveyrelatedrecord")
    op.drop_index(op.f("ix_surveymission_slug"), table_name="surveymission")
    op.drop_index(op.f("ix_surveymission_owner"), table_name="surveymission")
    op.drop_table("surveymission")
    op.drop_table("workflowstage")
    op.drop_index(op.f("ix_marinecampaign_slug"), table_name="marinecampaign")
    op.drop_index(op.f("ix_marinecampaign_owner"), table_name="marinecampaign")
    op.drop_table("marinecampaign")
    op.drop_table("domaintype")
    op.drop_table("datasetcategory")
    sa.Enum("DRAFT", "PUBLISHED", name="marinecampaignstatus").drop(op.get_bind())
    sa.Enum("DRAFT", "PUBLISHED", name="surveymissionstatus").drop(op.get_bind())
    sa.Enum("DRAFT", "PUBLISHED", name="surveyrelatedrecordstatus").drop(op.get_bind())
    # ### end Alembic commands ###
