"""added bbox_4326 to missions and records

Revision ID: 7aa0df84b581
Revises: 941230297c91
Create Date: 2025-10-24 18:06:58.742629

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "7aa0df84b581"
down_revision: Union[str, Sequence[str], None] = "941230297c91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_geospatial_column(
        "surveymission",
        sa.Column(
            "bbox_4326",
            Geometry(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
    )
    op.create_geospatial_index(
        "idx_surveymission_bbox_4326",
        "surveymission",
        ["bbox_4326"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.add_geospatial_column(
        "surveyrelatedrecord",
        sa.Column(
            "bbox_4326",
            Geometry(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
    )
    op.create_geospatial_index(
        "idx_surveyrelatedrecord_bbox_4326",
        "surveyrelatedrecord",
        ["bbox_4326"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_surveyrelatedrecord_bbox_4326",
        table_name="surveyrelatedrecord",
        postgresql_using="gist",
        column_name="bbox_4326",
    )
    op.drop_geospatial_column("surveyrelatedrecord", "bbox_4326")
    op.drop_geospatial_index(
        "idx_surveymission_bbox_4326",
        table_name="surveymission",
        postgresql_using="gist",
        column_name="bbox_4326",
    )
    op.drop_geospatial_column("surveymission", "bbox_4326")
    # ### end Alembic commands ###
