"""remove marine campaign model

Revision ID: 61c30a071362
Revises: 88b483de5639
Create Date: 2025-09-01 14:36:59.559267

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "61c30a071362"
down_revision: Union[str, Sequence[str], None] = "88b483de5639"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("surveymission_marine_campaign_id_fkey"),
        "surveymission",
        type_="foreignkey",
    )
    op.drop_column("surveymission", "marine_campaign_id")
    op.drop_index(op.f("ix_marinecampaign_slug"), table_name="marinecampaign")
    op.drop_index(op.f("ix_marinecampaign_owner"), table_name="marinecampaign")
    op.drop_table("marinecampaign")
    sa.Enum("DRAFT", "PUBLISHED", name="marinecampaignstatus").drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("DRAFT", "PUBLISHED", name="marinecampaignstatus").create(op.get_bind())
    op.add_column(
        "surveymission",
        sa.Column("marine_campaign_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("surveymission_marine_campaign_id_fkey"),
        "surveymission",
        "marinecampaign",
        ["marine_campaign_id"],
        ["id"],
    )
    # ### end Alembic commands ###
