"""added temporal columns to missions and records

Revision ID: 7496c4086b76
Revises: 38ceed03d957
Create Date: 2025-10-31 17:15:28.862519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "7496c4086b76"
down_revision: Union[str, Sequence[str], None] = "38ceed03d957"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "surveymission", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "surveymission", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "surveymission", sa.Column("temporal_extent_begin", sa.Date(), nullable=True)
    )
    op.add_column(
        "surveymission", sa.Column("temporal_extent_end", sa.Date(), nullable=True)
    )
    op.add_column(
        "surveyrelatedrecord", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "surveyrelatedrecord", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "surveyrelatedrecord",
        sa.Column("temporal_extent_begin", sa.Date(), nullable=True),
    )
    op.add_column(
        "surveyrelatedrecord",
        sa.Column("temporal_extent_end", sa.Date(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("surveyrelatedrecord", "temporal_extent_end")
    op.drop_column("surveyrelatedrecord", "temporal_extent_begin")
    op.drop_column("surveyrelatedrecord", "updated_at")
    op.drop_column("surveyrelatedrecord", "created_at")
    op.drop_column("surveymission", "temporal_extent_end")
    op.drop_column("surveymission", "temporal_extent_begin")
    op.drop_column("surveymission", "updated_at")
    op.drop_column("surveymission", "created_at")
    # ### end Alembic commands ###
