"""added asset discovery conf table

Revision ID: 1f2f2df99a93
Revises: 6277d3b8400f
Create Date: 2026-06-24 15:42:02.314265

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "1f2f2df99a93"
down_revision: Union[str, Sequence[str], None] = "6277d3b8400f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assetdiscoveryconfiguration",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "relative_path_regexp", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("workflow_stage_id", sa.Uuid(), nullable=True),
        sa.Column("dataset_category_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset_category_id"], ["datasetcategory.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workflow_stage_id"], ["workflowstage.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_assetdiscoveryconfiguration_dataset_category_id"),
        "assetdiscoveryconfiguration",
        ["dataset_category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assetdiscoveryconfiguration_workflow_stage_id"),
        "assetdiscoveryconfiguration",
        ["workflow_stage_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_assetdiscoveryconfiguration_workflow_stage_id"),
        table_name="assetdiscoveryconfiguration",
    )
    op.drop_index(
        op.f("ix_assetdiscoveryconfiguration_dataset_category_id"),
        table_name="assetdiscoveryconfiguration",
    )
    op.drop_table("assetdiscoveryconfiguration")
    # ### end Alembic commands ###
