"""added additional statuses

Revision ID: 7e83e5c4c2d1
Revises: c31d96af09db
Create Date: 2026-06-09 10:15:59.782045

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa
import sqlmodel  # noqa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "7e83e5c4c2d1"
down_revision: Union[str, Sequence[str], None] = "c31d96af09db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="surveyrelatedrecordstatus",
        new_values=[
            "DRAFT",
            "PUBLISHED",
            "UNDER_DERIVATION",
            "UNDER_DISCOVERY",
            "UNDER_EXPORT",
            "UNDER_VALIDATION",
            "UNDER_PARSING",
        ],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="surveyrelatedrecord",
                column_name="status",
            )
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="surveymissionstatus",
        new_values=[
            "DRAFT",
            "PUBLISHED",
            "UNDER_DISCOVERY",
            "UNDER_PARSING",
            "UNDER_VALIDATION",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="surveymission", column_name="status"
            )
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="projectstatus",
        new_values=[
            "DRAFT",
            "PUBLISHED",
            "UNDER_DISCOVERY",
            "UNDER_PARSING",
            "UNDER_VALIDATION",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="project", column_name="status"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="projectstatus",
        new_values=["DRAFT", "PUBLISHED", "UNDER_PARSING", "UNDER_VALIDATION"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="project", column_name="status"
            )
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="surveymissionstatus",
        new_values=["DRAFT", "PUBLISHED", "UNDER_PARSING", "UNDER_VALIDATION"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="surveymission", column_name="status"
            )
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="surveyrelatedrecordstatus",
        new_values=[
            "DRAFT",
            "PUBLISHED",
            "UNDER_DERIVATION",
            "UNDER_EXPORT",
            "UNDER_VALIDATION",
            "UNDER_PARSING",
        ],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="surveyrelatedrecord",
                column_name="status",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
