"""added media_type to asset discovery conf

Revision ID: b40c4fbe7472
Revises: 1f2f2df99a93
Create Date: 2026-07-22 12:32:33.500892

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "b40c4fbe7472"
down_revision: Union[str, Sequence[str], None] = "1f2f2df99a93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assetdiscoveryconfiguration",
        sa.Column("media_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assetdiscoveryconfiguration", "media_type")
    # ### end Alembic commands ###
