"""added user table

Revision ID: c4061cb6da28
Revises: f12ba98fcd56
Create Date: 2026-03-22 20:18:25.906028

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "c4061cb6da28"
down_revision: Union[str, Sequence[str], None] = "f12ba98fcd56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appuser",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False
        ),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("appuser")
    # ### end Alembic commands ###
