"""drop domain type table

Revision ID: 6277d3b8400f
Revises: 8e8083330bab
Create Date: 2026-06-24 15:19:49.917108

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "6277d3b8400f"
down_revision: Union[str, Sequence[str], None] = "8e8083330bab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("surveyrelatedrecord_domain_type_id_fkey"),
        "surveyrelatedrecord",
        type_="foreignkey",
    )
    op.drop_column("surveyrelatedrecord", "domain_type_id")
    op.drop_table("domaintype")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domaintype",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "surveyrelatedrecord",
        sa.Column("domain_type_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("surveyrelatedrecord_domain_type_id_fkey"),
        "surveyrelatedrecord",
        "domaintype",
        ["domain_type_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
