"""removed record relative path

Revision ID: 8e8083330bab
Revises: 7e83e5c4c2d1
Create Date: 2026-06-21 19:59:56.214156

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "8e8083330bab"
down_revision: Union[str, Sequence[str], None] = "7e83e5c4c2d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("surveyrelatedrecord", "relative_path")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "surveyrelatedrecord",
        sa.Column("relative_path", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
