"""added media_type to record

Revision ID: 94e06172bb9b
Revises: b40c4fbe7472
Create Date: 2026-07-24 10:03:03.858018

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "94e06172bb9b"
down_revision: Union[str, Sequence[str], None] = "b40c4fbe7472"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recordasset",
        sa.Column("media_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recordasset", "media_type")
    # ### end Alembic commands ###
