"""added implicit crs to survey mission

Revision ID: 51539465154f
Revises: 94e06172bb9b
Create Date: 2026-07-31 11:39:29.524522

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "51539465154f"
down_revision: Union[str, Sequence[str], None] = "94e06172bb9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "surveymission",
        sa.Column("implicit_crs", sa.Integer(), server_default="4326", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("surveymission", "implicit_crs")
    # ### end Alembic commands ###
